version: '3.5'
services:
  database:
    container_name: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - db_volume:/var/lib/postgresql
  app:
    build: ../IS601_RESTfulAPI/blog-api

volumes:
  db_volume: